language: go
go:
  - 1.2
  - 1.3
  - tip
install:
  - go get golang.org/x/tools/cmd/cover || true
  - go get code.google.com/p/go.tools/cmd/cover || true
  - go get github.com/robertkrimen/otto
  - go get github.com/howeyc/fsnotify
  - go get gopkg.in/fsnotify.v0
  - go get github.com/robfig/gettext-go
script:
  - go test -cover github.com/robfig/soy/...
