language: go
go:
  - 1.2
install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/robertkrimen/otto
  - go get code.google.com/p/go.exp/fsnotify
script:
  - go test -cover github.com/robfig/soy/...
